import {StyleSheet} from 'react-native';
import {Colors, Fonts} from '../../../Assets/Assets';
import Scale from '../../../Helper/Responsive';

export default StyleSheet.create({
  container: {backgroundColor: Colors.White, flex: 1, marginTop: Scale(22)},
  headerText: {
    fontFamily: Fonts.proximanova_bold,
    color: Colors.Grey400,
    fontSize: Scale(16),
    paddingHorizontal: Scale(5),
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Scale(15),
  },
  contentContainer: {paddingHorizontal: Scale(20)},
  shipmentDetailsContainer: {
    padding: Scale(15),
    backgroundColor: Colors.contentBg,
    borderRadius: Scale(9),
    marginTop: Scale(15),
    paddingHorizontal: Scale(18),
  },
  itemHeader: {flexDirection: 'row', alignItems: 'center', gap: Scale(15)},
  shipmentTypeText: {
    fontFamily: Fonts.proximanova_bold,
    color: Colors.Black,
    fontSize: Scale(14),
  },
  shipmentTypeBadge: {
    padding: Scale(5),
    borderRadius: Scale(7),
    paddingHorizontal: Scale(8),
  },
  shipmentTypeLabel: {
    color: Colors.White,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(12),
  },
  agentIdText: {
    marginTop: Scale(10),
    color: Colors.Grey300,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(14),
  },
  textInput: {
    backgroundColor: Colors.White,
    paddingVertical: Scale(5),
    borderRadius: Scale(10),
    marginTop: Scale(8),
    color: Colors.Grey400,
    fontSize: Scale(16),
    paddingHorizontal: Scale(15),
    fontFamily: Fonts.proximanova_regular,
    borderWidth: Scale(0.5),
    borderColor: Colors.Grey100,
  },
  row: {flexDirection: 'row', alignItems: 'center', marginTop: Scale(16)},
  rowItem: {flex: 0.5},
  rowItemHeader: {
    color: Colors.Black,
    fontFamily: Fonts.proximanova_bold,
    fontSize: Scale(14),
  },
  rowItemText: {
    color: Colors.Grey300,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(14),
  },
  shipInfoContainer: {
    padding: Scale(15),
    backgroundColor: Colors.contentBg,
    borderRadius: Scale(9),
    marginTop: Scale(15),
    paddingHorizontal: Scale(18),
  },
  shipInfo1: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickDateSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0.5,
    gap: Scale(8),
  },
  imgSec: {
    backgroundColor: Colors.imgBg,
    padding: Scale(8),
    borderRadius: Scale(5),
    alignSelf: 'flex-start',
  },
  icon: {height: Scale(15), width: Scale(15)},
  pickUpText: {
    color: Colors.Black,
    fontFamily: Fonts.proximanova_bold,
    fontSize: Scale(14),
  },
  dateTimeText: {
    color: Colors.Grey300,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(14),
  },
  shipmentTypeText: {
    fontFamily: Fonts.proximanova_bold,
    color: Colors.Black,
    fontSize: Scale(14),
  },
  shipmentTypeBadge: {
    padding: Scale(5),
    borderRadius: Scale(7),
    paddingHorizontal: Scale(8),
  },
  shipmentTypeLabel: {
    color: Colors.White,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(12),
  },
  pickUp: {
    fontFamily: Fonts.proximanova_bold,
    fontSize: Scale(14),
    color: Colors.Black,
  },
  pickUpData: {
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(14),
    color: Colors.Grey300,
    marginTop: Scale(3),
  },
  pickupLocation: {
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    paddingBottom: Scale(30),
    paddingHorizontal: Scale(30),
  },
  dot: {
    position: 'absolute',
    height: Scale(12),
    width: Scale(12),
  },
  bottomButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: Scale(10),
    marginTop: Scale(30),
    position: 'absolute',
    bottom: 10,
    paddingHorizontal: Scale(20),
  },
  statusText: {
    color: Colors.Grey300,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(14),
  },
  statusView: {
    backgroundColor: Colors.White,
    paddingVertical: Scale(5),
    borderRadius: Scale(8),
    marginTop: Scale(8),
    borderWidth: Scale(0.5),
    borderColor: Colors.Grey100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Scale(10),
  },
  status: {
    fontSize: Scale(16),
    fontFamily: Fonts.proximanova_regular,
  },
  shipmentStatusView: {
    backgroundColor: Colors.White,
    borderRadius: 10,
    padding: 10,
  },
  statusModel: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: Scale(1),
    borderRadius: Scale(10),
    margin: Scale(10),
    borderColor: Colors.Grey100,
    padding: Scale(8),
    gap: Scale(10),
    paddingVertical: Scale(10),
  },
  statusModelImg: {
    height: Scale(22),
    width: Scale(22),
    marginLeft: 10,
  },
  statusModelText: {
    color: Colors.Black,
    fontFamily: Fonts.proximanova_regular,
    fontSize: Scale(16),
  },
  rejectView: {
    backgroundColor: Colors.White,
    borderRadius: 10,
    padding: 10,
  },
  rejectHeaderView: {alignItems: 'center', paddingHorizontal: Scale(12)},
  rejectImg: {height: Scale(60), width: Scale(60)},
  rejectLabel: {
    color: Colors.Grey400,
    fontFamily: Fonts.proximanova_bold,
    fontSize: Scale(18),
    marginTop: Scale(8),
  },
  rejectBio: {
    fontSize: Scale(16),
    fontFamily: Fonts.proximanova_regular,
    color: Colors.Grey300,
    textAlign: 'center',
    marginTop: Scale(10),
  },
  rejectButtonView: {
    flexDirection: 'row',
    width: '100%',
    gap: Scale(10),
    marginTop: Scale(30),
    paddingHorizontal: Scale(10),
    marginLeft: Scale(-3),
  },
});
