export const Labels = {
  language: 'Choose Language',
  english: 'English',
  french: 'Français (French)',
  continue: 'Continue',
  started: "Let's Get Started",
  bio: 'Effortlessly track your shipments in real-time, ensuring timely deliveries.',
  Email: 'Email',
  otp: 'OTP Verification',
  otpBio: 'We have just sent OTP code to your below email id',
  ShipmentData: 'Shipment Data',
  DeliveriesAssigned: 'Deliveries Assigned',
  CompletedDeliveries: 'Completed Deliveries',
  PendingDeliveries: 'Pending Deliveries',
  DelayedDeliveries: 'Delayed Deliveries',
  logout: 'Logout',
  Done: 'Done',
  Are_you_sure_you_want_to_logout: 'Are you sure you want to logout?',
  Notification: 'Notification',
  My_Delivery: 'My Delivery',
  Regular: 'Regular',
  Urgent: 'Urgent',
  Shipment_Type: 'Shipment Type',
  PickUp_Date: 'Pick-Up Date',
  PickUp_Time: 'Pick-Up Time',
  View_Details: 'View Details',
  Shipment_Details: 'Shipment Details',
  AgentID: 'Agent ID',
  ShipmentID: 'Shipment ID',
  Total_Charges: 'Total Charges',
  Shipment_Information: 'Shipment Information',
  PickUp_Location: 'Pick-Up Location',
  Drop_Location: 'Drop Location',
  Shipment_Status:'Shipment Status',
  Reject_Shipment_Delivery:'Reject Shipment Delivery',
};
