export const Labels = {
  language: 'Choose Language',
  english: 'English',
  french: 'Français (French)',
  continue: 'Continue',
  started: "Let's Get Started",
  bio: 'Effortlessly track your shipments in real-time, ensuring timely deliveries.',
  Email: 'Email',
  otp: 'OTP Verification',
  otpBio: 'We have just sent OTP code to your below email id',
  ShipmentData: 'Shipment Data',
  DeliveriesAssigned: 'Deliveries Assigned',
  CompletedDeliveries: 'Completed Deliveries',
  PendingDeliveries: 'Pending Deliveries',
  DelayedDeliveries: 'Delayed Deliveries',
  logout: 'Logout',
  Done: 'Done',
};
